### ISSUE TITLE
Feedback: Week 0

### ISSUE THREAD

**Issue by acabunoc** [mozilla/leadership-training#23]
Hello all!

How did you find Week 0: Introductions & Project Planning?

* What went well?
* What could be better?
* Is there anything you'd like to see more or less of during the program?

This program is here to help you! If there's anything you'd like to let us know, this is a great place. You're always welcome to send me an email (abby AT mozillafoundation.org)

**Comment by shamedian** [comment]
Hello! I had two comments regarding Cohort B:

- As people said during the call itself, Zoom was an absolutely great meeting platform! Being able to break out into smaller rooms was great (and easy!)

- I wish there was more time for Grant at the end, I think I recall his presentation was almost pushed to the next meeting due to some constraints. Maybe it would have helped to make the breakout sessions a bit smaller so he would have had more time?

Great meeting though! Loved it and looking forward to the rest of the program! :-)

**Comment by acabunoc** [comment]
Thanks @shamedian! Very helpful, we tried to be more mindful of time and I think that helped.

I'm closing this for now -- please feel free to continue adding comments if anyone else has some feedback on Week 0!
